import { LANGUAGE_IDS, type LanguageId } from '../config/schema.js';
import { baseNameOf, extensionOf } from '../shared/paths.js';

/**
 * File classification.
 *
 * Everything here is table-driven rather than branch-driven. Adding a language
 * is a row in `EXTENSION_LANGUAGE`, not a new `if`. That matters because the
 * connector claims fifteen languages: fifteen hand-written branches would rot,
 * and the table can be asserted against `LANGUAGE_IDS` in a test so a typo is a
 * failing build rather than a silently unindexed file type.
 */

const EXTENSION_LANGUAGE: Readonly<Record<string, LanguageId>> = {
  ts: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  tsx: 'tsx',
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'jsx',
  py: 'python',
  pyi: 'python',
  go: 'go',
  java: 'java',
  cs: 'csharp',
  rs: 'rust',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  hpp: 'cpp',
  hh: 'cpp',
  c: 'c',
  h: 'c',
  kt: 'kotlin',
  kts: 'kotlin',
  md: 'markdown',
  mdx: 'markdown',
  markdown: 'markdown',
  yml: 'yaml',
  yaml: 'yaml',
  json: 'json',
  jsonc: 'json',
  tf: 'terraform',
  tfvars: 'terraform',
  hcl: 'terraform',
  sql: 'sql',
};

/** Files with no extension, or whose name carries more signal than the extension. */
const FILENAME_LANGUAGE: Readonly<Record<string, LanguageId>> = {
  dockerfile: 'dockerfile',
  containerfile: 'dockerfile',
  'docker-compose.yml': 'yaml',
  'docker-compose.yaml': 'yaml',
  'package.json': 'json',
  'tsconfig.json': 'json',
  'go.mod': 'go',
  'go.sum': 'go',
};

/** Interpreters seen in shebangs, for extension-less executable scripts. */
const SHEBANG_LANGUAGE: readonly (readonly [RegExp, LanguageId])[] = [
  [/^#!.*\bpython[\d.]*\b/, 'python'],
  [/^#!.*\bnode\b/, 'javascript'],
  [/^#!.*\bts-node\b/, 'typescript'],
];

const BINARY_EXTENSIONS = new Set([
  'png', 'jpg', 'jpeg', 'gif', 'bmp', 'ico', 'webp', 'avif', 'tiff', 'svgz',
  'pdf', 'zip', 'gz', 'tgz', 'bz2', 'xz', 'zst', '7z', 'rar', 'jar', 'war',
  'so', 'dylib', 'dll', 'exe', 'bin', 'o', 'a', 'lib', 'obj', 'pdb',
  'class', 'pyc', 'pyo', 'wasm', 'node',
  'mp3', 'mp4', 'wav', 'ogg', 'webm', 'mov', 'avi', 'mkv',
  'ttf', 'otf', 'woff', 'woff2', 'eot',
  'db', 'sqlite', 'sqlite3', 'mdb', 'parquet', 'avro',
]);

/**
 * Markers that a file is machine-written. Generated code inflates every metric,
 * dominates search results, and is never what a developer means by "where is
 * this implemented" — so it is indexed but demoted, not hidden.
 */
const GENERATED_PATH_PATTERNS: readonly RegExp[] = [
  /(^|\/)(generated|__generated__|gen|autogen)\//i,
  /\.(pb|generated|g|designer)\.[a-z]+$/i,
  /(^|\/)migrations?\/\d+/i,
  /\.d\.ts$/,
  /_pb2(_grpc)?\.py$/,
  /(^|\/)zz_generated/i,
];

const GENERATED_HEADER = /^(?:.{0,4}\s*)(?:@generated\b|Code generated by |DO NOT EDIT|AUTO-?GENERATED)/im;

const TEST_PATH_PATTERNS: readonly RegExp[] = [
  /(^|\/)(tests?|__tests__|spec|specs|e2e|integration)\//i,
  /\.(test|spec)\.[a-z]+$/i,
  /(^|\/)test_[^/]+\.py$/,
  /[^/]+_test\.(go|py|rb)$/,
  /Tests?\.(java|cs|kt)$/,
];

export function languageOf(relPath: string, extensionOverrides: Record<string, LanguageId> = {}): LanguageId | null {
  const name = baseNameOf(relPath).toLowerCase();
  const byName = FILENAME_LANGUAGE[name];
  if (byName !== undefined) return byName;

  // `Dockerfile.prod`, `Dockerfile.dev` and friends.
  if (name.startsWith('dockerfile.')) return 'dockerfile';

  const extension = extensionOf(relPath);
  if (extension.length === 0) return null;
  return extensionOverrides[extension] ?? EXTENSION_LANGUAGE[extension] ?? null;
}

/** Second chance for extension-less files, using the first line of content. */
export function languageFromShebang(firstLine: string): LanguageId | null {
  for (const [pattern, language] of SHEBANG_LANGUAGE) {
    if (pattern.test(firstLine)) return language;
  }
  return null;
}

export function isBinaryExtension(relPath: string): boolean {
  return BINARY_EXTENSIONS.has(extensionOf(relPath));
}

/**
 * Content-based binary detection: a NUL byte in the first 8 KB. This is the
 * heuristic git itself uses, and it catches the cases the extension table
 * misses — a `.dat`, a `.pack`, an unrecognised proprietary format.
 */
export function looksBinary(sample: Uint8Array): boolean {
  const limit = Math.min(sample.length, 8192);
  for (let i = 0; i < limit; i += 1) {
    if (sample[i] === 0) return true;
  }
  return false;
}

export function isGeneratedPath(relPath: string): boolean {
  return GENERATED_PATH_PATTERNS.some((pattern) => pattern.test(relPath));
}

/** Checks the conventional `@generated` / `Code generated by` header banner. */
export function hasGeneratedHeader(source: string): boolean {
  return GENERATED_HEADER.test(source.slice(0, 512));
}

export function isTestPath(relPath: string): boolean {
  return TEST_PATH_PATTERNS.some((pattern) => pattern.test(relPath));
}

export function countLines(source: string): number {
  if (source.length === 0) return 0;
  let lines = 1;
  for (let i = 0; i < source.length; i += 1) {
    if (source.charCodeAt(i) === 10) lines += 1;
  }
  return lines;
}

/** Every language the classifier can actually produce; asserted against config in tests. */
export function classifiableLanguages(): ReadonlySet<LanguageId> {
  return new Set<LanguageId>([
    ...Object.values(EXTENSION_LANGUAGE),
    ...Object.values(FILENAME_LANGUAGE),
  ]);
}

export const ALL_LANGUAGE_IDS: readonly LanguageId[] = LANGUAGE_IDS;
