import { describe, expect, it } from 'vitest';
import {
  countLines,
  hasGeneratedHeader,
  isBinaryExtension,
  isGeneratedPath,
  isTestPath,
  languageFromShebang,
  languageOf,
  looksBinary,
} from '../../src/indexer/classifier.js';

describe('languageOf', () => {
  it.each([
    ['src/index.ts', 'typescript'],
    ['src/App.tsx', 'tsx'],
    ['main.py', 'python'],
    ['cmd/server/main.go', 'go'],
    ['Cargo/src/lib.rs', 'rust'],
    ['Dockerfile', 'dockerfile'],
    ['Dockerfile.production', 'dockerfile'],
    ['infra/main.tf', 'terraform'],
    ['README.md', 'markdown'],
  ])('classifies %s', (path, expected) => {
    expect(languageOf(path)).toBe(expected);
  });

  it('returns null for unknown extensions', () => {
    expect(languageOf('data.parquet')).toBeNull();
  });

  it('honours user overrides', () => {
    expect(languageOf('App.vue', { vue: 'javascript' })).toBe('javascript');
  });

  it('prefers filename over extension where the name carries more signal', () => {
    expect(languageOf('go.mod')).toBe('go');
  });
});

describe('languageFromShebang', () => {
  it('detects python', () => {
    expect(languageFromShebang('#!/usr/bin/env python3')).toBe('python');
  });

  it('detects node', () => {
    expect(languageFromShebang('#!/usr/bin/env node')).toBe('javascript');
  });

  it('returns null for a plain first line', () => {
    expect(languageFromShebang('const x = 1')).toBeNull();
  });
});

describe('binary detection', () => {
  it('recognises binary extensions', () => {
    expect(isBinaryExtension('logo.png')).toBe(true);
    expect(isBinaryExtension('index.ts')).toBe(false);
  });

  it('finds a NUL byte in content', () => {
    expect(looksBinary(new Uint8Array([104, 105, 0, 1]))).toBe(true);
    expect(looksBinary(new Uint8Array([104, 105]))).toBe(false);
  });

  it('only samples the first 8 KB', () => {
    // Must be filled with real content first: a fresh Uint8Array is entirely
    // NUL bytes, so the detector would trip on byte 0 and the 8 KB cap this
    // test exists to check would never be reached.
    const buffer = new Uint8Array(10_000).fill(0x41);
    buffer[9_000] = 0;

    expect(looksBinary(buffer)).toBe(false);
  });

  it('finds a NUL byte that falls inside the sampled window', () => {
    const buffer = new Uint8Array(10_000).fill(0x41);
    buffer[8_000] = 0;

    expect(looksBinary(buffer)).toBe(true);
  });
});

describe('generated detection', () => {
  it.each([
    'src/__generated__/schema.ts',
    'api/service.pb.go',
    'types/index.d.ts',
    'proto/user_pb2.py',
  ])('flags %s by path', (path) => {
    expect(isGeneratedPath(path)).toBe(true);
  });

  it('does not flag ordinary source', () => {
    expect(isGeneratedPath('src/auth/jwt.ts')).toBe(false);
  });

  it('reads the conventional header banner', () => {
    expect(hasGeneratedHeader('// Code generated by protoc. DO NOT EDIT.\n')).toBe(true);
    expect(hasGeneratedHeader('/* @generated */\n')).toBe(true);
    expect(hasGeneratedHeader('// a normal comment\n')).toBe(false);
  });
});

describe('test detection', () => {
  it.each([
    'src/auth/jwt.test.ts',
    'tests/integration/api.ts',
    'app/test_models.py',
    'pkg/server_test.go',
  ])('flags %s', (path) => {
    expect(isTestPath(path)).toBe(true);
  });

  it('does not flag production code that merely contains the word', () => {
    expect(isTestPath('src/latest/index.ts')).toBe(false);
  });
});

describe('countLines', () => {
  it('counts an empty string as zero', () => {
    expect(countLines('')).toBe(0);
  });

  it('counts a trailing newline as an extra line', () => {
    expect(countLines('a\nb\n')).toBe(3);
  });
});
